name: Build and release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
permissions:
  id-token: write
  pages: write
  contents: write
  deployments: write
  packages: write
 
jobs:
  build_arythmatik:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ["A-RYTH-MATIK"]
        firmware: ["ARYTHMATIK_Euclid", "ARYTHMATIK_Gate"]
        board: ["arduino:avr:nano"]
        include:
          - board: arduino:avr:nano
            boardpath: nano

    steps:

      - name: Checkout A-RYTH-MATIK repo
        uses: actions/checkout@v4
        with:
           repository: modulove/A-RYTH-MATIK
           
      - name: Display repo
        run: ls -R

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: Install Arduino platform and libraries
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli core install lgt8fx:avr --additional-urls https://raw.githubusercontent.com/dbuezas/lgt8fx/master/package_lgt8fx_index.json
          arduino-cli lib install "Adafruit GFX Library"
          arduino-cli lib install "Adafruit SSD1306"
          arduino-cli lib install FastGPIO
          arduino-cli lib install SimpleRotary
          arduino-cli lib install Encoder
          
      - name: Display structure of workdir
        run: ls -R
        
      - name: Compile sketch and rename output file for release
        
        run: |
          mkdir -p ./build/${{ matrix.boardpath }}
          mkdir -p ./release
          arduino-cli compile -v -b ${{ matrix.board}} Firmware/${{ matrix.firmware}}/${{ matrix.firmware}}.ino -e --output-dir=./build/${{ matrix.boardpath }}
          cp ./build/${{ matrix.boardpath }}/${{ matrix.firmware }}.ino.hex ./release/${{ matrix.module}}_${{ matrix.firmware }}.${{ matrix.boardpath }}.hex

      - name: Display builddir
        run: ls -R ./build

      - name: Display releasedir
        run: ls -R ./release

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts-${{ matrix.boardpath }}-${{ matrix.firmware }}
          path: ./release/*.hex

  release:
    needs: [build_arythmatik]

    runs-on: ubuntu-latest
    permissions:
        pages: write
        id-token: write
        contents: write
        
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          path: releases/

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release and attach files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: releases/**/*.hex
