name: Build and release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_arythmatik:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ["A-RYTH-MATIK"]
        firmware: ["BitGarden", "Uncertainty", "TimeBandit"]
        board: ["arduino:avr:nano", "arduino:avr:nano:cpu=atmega328old", "lgt8fx:avr:328"]
        include:
          - board: arduino:avr:nano
            boardpath: nano
          - board: arduino:avr:nano:cpu=atmega328old
            boardpath: nanoOldBootloader
          - board: lgt8fx:avr:328
            boardpath: lgt8f328p

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: Install Arduino platform and libraries
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli core install lgt8fx:avr --additional-urls https://raw.githubusercontent.com/dbuezas/lgt8fx/master/package_lgt8fx_index.json
          arduino-cli lib install "Adafruit GFX Library"
          arduino-cli lib install "Adafruit SSD1306"
          arduino-cli lib install SimpleRotary
      - name: Compile sketch and rename output file for release
        working-directory: ./${{ matrix.module}}
        run: |
          arduino-cli compile -v -b ${{ matrix.board}} ${{ matrix.firmware}} -e --output-dir=./build/${{ matrix.boardpath }}
          arduino-cli compile -v -b ${{ matrix.board}} --build-property "build.extra_flags=-DENCODER_REVERSED" ${{ matrix.firmware}} -e --output-dir=./build_reversed/${{ matrix.boardpath }}
          mkdir -p ./release
          cp ./build/${{ matrix.boardpath }}/${{ matrix.firmware }}.ino.hex ./release/${{ matrix.module}}_${{ matrix.firmware }}.${{ matrix.boardpath }}.hex
          cp ./build_reversed/${{ matrix.boardpath }}/${{ matrix.firmware }}.ino.hex ./release/${{ matrix.module}}_${{ matrix.firmware }}.${{ matrix.boardpath }}.reversed.hex

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts-${{ matrix.boardpath }}-${{ matrix.firmware }}
          path: ./${{ matrix.module}}/release/*.hex


  build_synclfo:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          module: ["SyncLFO"]
          firmware: ["ADSR", "Baby4", "GenerativeSequencer", "MultiModeEnv", "Polyrhythm", "PerlinNoise", "TriggerDelay"]
          board: ["arduino:avr:nano", "arduino:avr:nano:cpu=atmega328old", "lgt8fx:avr:328"]
          include:
            - board: arduino:avr:nano
              boardpath: nano
            - board: arduino:avr:nano:cpu=atmega328old
              boardpath: nanoOldBootloader
            - board: lgt8fx:avr:328
              boardpath: lgt8f328p

    steps:
        - name: Clone repo
          uses: actions/checkout@master

        - name: Setup Arduino CLI
          uses: arduino/setup-arduino-cli@v1.1.1

        - name: Install Arduino platform and libraries
          run: |
            arduino-cli core update-index
            arduino-cli core install arduino:avr
            arduino-cli core install lgt8fx:avr --additional-urls https://raw.githubusercontent.com/dbuezas/lgt8fx/master/package_lgt8fx_index.json
            arduino-cli lib install FastLED

        - name: Compile sketch and rename output file for release
          working-directory: ./${{ matrix.module}}
          run: |
            arduino-cli compile -v -b ${{ matrix.board}} ${{ matrix.firmware}} -e --output-dir=./build/${{ matrix.boardpath }}
            mkdir -p ./release && cp ./build/${{ matrix.boardpath }}/${{ matrix.firmware }}.ino.hex ./release/${{ matrix.module}}_${{ matrix.firmware }}.${{ matrix.boardpath }}.hex

        - name: Upload release artifacts
          uses: actions/upload-artifact@v4
          with:
            name: release-artifacts-${{ matrix.boardpath}}-${{ matrix.firmware }}
            path: ./${{ matrix.module}}/release/*.hex

  release:
    needs: [build_arythmatik, build_synclfo]

    runs-on: ubuntu-latest
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          path: releases/

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release and attach files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: releases/**/*.hex

  hugo_deploy:
    needs: [release]
    uses: ./.github/workflows/hugo.yml
